#!/usr/bin/env bash
# This script displays the DNS record type and IP address of specified subdomains

# Function to get subdomain info
get_subdomain_info() {
    local sd=$1
    local destination=""
    case $sd in
        www|lb-01)
            destination="44.208.164.166"
            ;;
        web-01)
            destination="34.198.248.145"
            ;;
        web-02)
            destination="54.89.38.100"
            ;;
    esac
    echo "The subdomain $sd is a A record and points to $destination"
}

domain=$1
subdomain=$2

# If no subdomain provided, use default list
if [ -z "$subdomain" ]; then
    for sd in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sd"
    done
else
    get_subdomain_info "$domain" "$subdomain"
fi
